### ISSUE TITLE
nested describe keywords

### ISSUE THREAD

**Issue by ShockiTV** [paolo/smithy-describe#1]
We like to nest describe keywords, not context keywords.
From where is this context nested spec ?
We would really appreciate if we could also use nested describe instead.

**Comment by paolo** [comment]
@ShockiTV I feel your pain, I'm still trying to find a way to address this problem. whenever I use describe on inner functions, it grabs the one defined globally, therefore messing up the Tinytests description format.
I'll keep you posted on this, I'll see if I can get help from some javascript gurus :)

**Comment by paolo** [comment]
@ShockiTV Hey, good news, after trying different approaches, I found a simple solution and should be working now with version 1.0.1. can you confirm is working for you?
BTW, context support is still there, so your current tests should still work with 1.0.1

**Comment by paolo** [comment]
closing
